# バージョン 3.3 記法を使う
version: "3.3"

# コンテナ定義
services:

  # WordPress（CMS 本体）
  wordpress:
    # 公式イメージを使う
    # さくらインターネットで使えるバージョンに統一
    image: wordpress:4.8.3-php7.1-apache

    # データベースとリンクする
    # db というホスト名で接続できる
    # <host>:<container>
    links:
      - mysql:db

    # ポートを公開する
    # WordPress はポート 80 を前提とした作りのようなので 80 を指定
    # <host>:<container>
    ports:
      - 80:80

    # 設定値のうち秘密の値は env ファイルを作成し
    # key=value
    # の形式で記載する
    env_file:
      - mysql.env
      - wp-config.env

    # 本番環境と異なる設定値のうち、秘密ではないもの
    environment:
      - DB_HOST=db
      - WP_DEBUG=1
      - WP_DEBUG_LOG=1
      - WP_DEBUG_DISPLAY=0

    # <host>:<container>
    volumes:
      # 設定値
      - ./html/.htaccess:/var/www/html/.htaccess
      - ./html/wp-config.php:/var/www/html/wp-config.php

      # プラグイン
      - ./html/wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins

      # テーマを直接編集するため、ボリュームとして設定する
      - ./html/wp-content/themes/cross2014:/var/www/html/wp-content/themes/cross2014
      - ./html/wp-content/themes/cross2018:/var/www/html/wp-content/themes/cross2018

      # 古い静的ページ
      - ./html/gelsympo2007:/var/www/html/gelsympo2007

      # ダウンロードしたアップデートやプラグインを永続化する
      - ./wordpress:/var/www/html

  # MySQL データベース
  mysql:
    # 公式イメージを使う
    # さくらインターネットで使えるバージョンに統一
    image: mysql:5.5.57

    # 設定値のうち秘密の値は env ファイルを作成し
    # key=value
    # の形式で記載する
    env_file:
      - mysql.env

    # データ内容を保持する
    volumes:
      - ./mysql:/var/lib/mysql

  # データベース管理画面
  # 通常時は使わないが、特殊なメンテナンスやデータ移行時に使う
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:edge-4.8
    links:
      - mysql:db
    ports:
      - 8080:80
